<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="alejandrolammbp.lan" failures="1" tests="1" name="Default test(failed)" time="0.047" errors="0" timestamp="2021-12-02T16:30:25 CST">
  <testcase classname="com.code.CodePractice" name="aPrintHi" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at com.code.CodePractice.aPrintHi(CodePractice.java:129)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- aPrintHi -->
  <testcase classname="com.code.CodePractice" name="findNumberPosition" time="0.0">
    <ignored/>
  </testcase> <!-- findNumberPosition -->
  <testcase classname="com.code.CodePractice" name="deleteLetters" time="0.0">
    <ignored/>
  </testcase> <!-- deleteLetters -->
  <testcase classname="com.code.CodePractice" name="removeNumber" time="0.0">
    <ignored/>
  </testcase> <!-- removeNumber -->
  <testcase classname="com.code.CodePractice" name="countRepeatedNumbers" time="0.0">
    <ignored/>
  </testcase> <!-- countRepeatedNumbers -->
  <testcase classname="com.code.CodePractice" name="reverseSentence" time="0.0">
    <ignored/>
  </testcase> <!-- reverseSentence -->
</testsuite> <!-- Default test(failed) -->
